-- Application tables. Better Auth's own tables (user, session, account,
-- verification, subscription) are generated by its CLI into 0002_better_auth.sql
-- -- see web/README or `npm run db:generate`.

-- Append-only token ledger. Balance is SUM(delta); nothing is ever updated in
-- place, which is what makes the spend path safe without transactions (D1 has
-- no interactive transactions).
CREATE TABLE IF NOT EXISTS credit_ledger (
  id         TEXT    PRIMARY KEY,
  userId     TEXT    NOT NULL,
  delta      INTEGER NOT NULL,
  reason     TEXT    NOT NULL, -- signup_grant | subscription_grant | generate | refund
  -- Idempotency key. Stripe delivers webhooks at least once, so grants carry the
  -- Stripe event id here and a redelivery hits this constraint instead of
  -- granting twice. NULL for debits (SQLite allows many NULLs under UNIQUE).
  externalId TEXT    UNIQUE,
  createdAt  INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_credit_ledger_user ON credit_ledger (userId);

CREATE TABLE IF NOT EXISTS generation (
  id          TEXT    PRIMARY KEY,
  userId      TEXT    NOT NULL,
  runpodJobId TEXT,
  prompt      TEXT    NOT NULL,
  status      TEXT    NOT NULL, -- QUEUED | COMPLETED | FAILED
  imageKey    TEXT,             -- R2 object key, served via /i/:key
  width       INTEGER,
  height      INTEGER,
  steps       INTEGER,
  seed        INTEGER,
  generateMs  INTEGER,          -- GPU time reported by the worker
  queueMs     INTEGER,          -- wall time from submit to completion
  coldStart   INTEGER DEFAULT 0,
  gpu         TEXT,
  error       TEXT,
  createdAt   INTEGER NOT NULL,
  completedAt INTEGER
);

CREATE INDEX IF NOT EXISTS idx_generation_user ON generation (userId, createdAt DESC);
